
spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://47.75.55.158:3306/mydb?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: 136125842
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8080
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml

